schemes:
- scheme: chibi
  docker-tag: head
  init-cmd: |
    apt-get update && apt-get install -y git ca-certificates gcc make libffi-dev
    git clone https://github.com/ashinn/chibi-scheme.git --depth=1
    make -j8 -C chibi-scheme
    make -j8 -C chibi-scheme install
    snow-chibi install retropikzel.compile-r7rs
  stages:
      - name: tap
        cmd: compile-r7rs -o tap retropikzel/tap/test.scm && ./tap


