ARG SCHEME=chibi
ARG IMAGE=${SCHEME}:head
FROM debian:trixie AS build
RUN apt-get update && apt-get install -y \
git ca-certificates make gcc libffi-dev libffi-dev wget xz-utils libcurl4
RUN mkdir ${HOME}/.snow && echo "()" > ${HOME}/.snow/config.scm
WORKDIR /build
RUN wget https://gitlab.com/-/project/6808260/uploads/094ce726ce3c6cf8c14560f1e31aaea0/akku-1.1.0.amd64-linux.tar.xz \
    && tar -xf akku-1.1.0.amd64-linux.tar.xz \
    && mv akku-1.1.0.amd64-linux akku
#RUN git clone https://github.com/ashinn/chibi-scheme.git --depth=2
RUN git clone https://github.com/Retropikzel/chibi-scheme.git --branch=snow-chibi-kawa-fixes --depth=1
RUN git clone https://codeberg.org/retropikzel/compile-scheme.git --depth=2
WORKDIR /build/chibi-scheme
RUN make
RUN make install
WORKDIR /build/compile-scheme
RUN make build-gauche

ARG SCHEME=chibi
ARG IMAGE=${SCHEME}:head
FROM schemers/${IMAGE}
RUN apt-get update && apt-get install -y \
    make gcc libffi-dev libcurl4 gauche lighttpd
RUN mkdir ${HOME}/.snow && echo "()" > ${HOME}/.snow/config.scm
COPY --from=build /build /build
ARG SCHEME=chibi
WORKDIR /build/compile-scheme
RUN make install
WORKDIR /build/chibi-scheme
RUN make install
WORKDIR /build/akku
RUN bash install.sh
ENV PATH=/root/.local/bin:${PATH}
RUN akku update
WORKDIR /workdir
COPY fcgi-lighttpd.conf .
RUN snow-chibi --impls=${SCHEME} --always-yes install "(srfi 60)"
RUN snow-chibi --impls=${SCHEME} --always-yes install "(srfi 64)"
RUN if [ "${SCHEME}" != "gauche" ]; then snow-chibi --impls=${SCHEME} --always-yes install "(srfi 106)"; fi
RUN if [ "${SCHEME}" != "gauche" ]; then snow-chibi --impls=${SCHEME} --always-yes install --install-source-dir=. --install-library-dir=. "(srfi 106)"; fi
RUN snow-chibi --impls=${SCHEME} --always-yes install "(srfi 180)"
COPY Makefile .
COPY retropikzel retropikzel/
RUN akku install loko-srfi
