FROM debian:trixie-slim
RUN apt-get update && apt-get install -y \
    gcc ca-certificates libffi-dev docker.io make curl
RUN git clone https://github.com/ashinn/chibi-scheme.git --depth=1 \
    && cd chibi-scheme \
    && chibi-scheme \
    && chibi-scheme install
RUN snow-chibi install --impls=chibi retropikzel.test-r7rs
