FROM debian:trixie-slim
RUN apt-get update && apt-get install -y \
    gcc ca-certificates libffi-dev docker.io make
RUN git clone https://github.com/ashinn/chibi-scheme.git --depth=1 \
    && make -C chibi-scheme \
    && make -C chibi-scheme install
RUN snow-chibi install --impls=chibi --always-yes retropikzel.test-r7rs
