(import (scheme base)
        (scheme write)
        (scheme read)
        (scheme char)
        (scheme file)
        (scheme process-context)
        (retropikzel tap)
        (retropikzel LIBRARY)
        (srfi 64))

(test-runner-current (tap-runner))
