(define-library
  (retropikzel fcgi)
  (import (scheme base)
          (scheme write)
          (scheme char)
          (scheme file)
          (scheme complex)
          (scheme process-context)
          (srfi 60)
          (srfi 106))
  (export handle-request)
  (include "fcgi.scm"))
