(define-library
  (retropikzel scgi)
  (import (scheme base)
          (scheme write)
          (scheme char)
          (scheme file)
          (scheme process-context)
          (srfi 106)
          (retropikzel net))
  (export handle-request)
  (include "scgi.scm"))
