(define-library
  (retropikzel wasm)
  (import (scheme base)
          (scheme read)
          (scheme write)
          (srfi 1)
          (r6rs bytevectors))
  (export wat-module->r7rs-library)
  (include "wasm/util.scm")
  (include "wasm.scm"))
